# Generated by Django 5.0.6 on 2024-06-21 07:07

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('link', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Инфо главной страницы',
                'verbose_name_plural': 'Инфо главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=3.2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecondPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('link', models.TextField(max_length=100)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_app.generalpage')),
            ],
            options={
                'verbose_name': 'Инфо второй страницы',
                'verbose_name_plural': 'Инфо второй страницы',
            },
        ),
        migrations.CreateModel(
            name='ThirdPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=100)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_app.secondpage')),
            ],
            options={
                'verbose_name': 'Инфо третьей страницы',
                'verbose_name_plural': 'Инфо третьей страницы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_link', models.TextField(max_length=300)),
                ('general_link_text', models.TextField(max_length=300)),
                ('mark_link', models.TextField(max_length=300)),
                ('mark_link_text', models.TextField(max_length=300)),
                ('model_link', models.TextField(max_length=300)),
                ('model_link_text', models.TextField(max_length=300)),
                ('year', models.IntegerField(default=1910)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('detailed_link', models.TextField(max_length=300)),
                ('detailed_link_text', models.TextField(max_length=300)),
                ('description_in_general', models.TextField(max_length=300)),
                ('card_header', models.TextField(max_length=300)),
                ('card_price_primary', models.IntegerField()),
                ('card_price_secondary', models.IntegerField()),
                ('card_commercial', models.TextField(max_length=300)),
                ('card_params', models.TextField(max_length=400)),
                ('card_short_description', models.TextField(max_length=500)),
                ('card_short_modification', models.TextField(max_length=500)),
                ('card_all_param_button_href', models.TextField(max_length=300)),
                ('card_location', models.TextField(max_length=300)),
                ('vin', models.TextField(max_length=100)),
                ('image_links', models.TextField(max_length=1000)),
                ('card_comment_text', models.TextField(max_length=10000)),
                ('card_exchange', models.TextField(max_length=500)),
                ('exterior', models.TextField(max_length=1000)),
                ('security_systems', models.TextField(max_length=1000)),
                ('pillows', models.TextField(max_length=500)),
                ('help_systems', models.TextField(max_length=1000)),
                ('interior', models.TextField(max_length=1000)),
                ('comfort', models.TextField(max_length=1000)),
                ('heating', models.TextField(max_length=500)),
                ('climate', models.TextField(max_length=500)),
                ('multimedia', models.TextField(max_length=1000)),
                ('headlights', models.TextField(max_length=500)),
                ('card_finance_image', models.TextField(max_length=300)),
                ('card_finance_description', models.TextField(max_length=300)),
                ('card_finance_item_subtitle', models.TextField(max_length=300)),
                ('card_average_price', models.TextField(max_length=100)),
                ('card_average_price_description', models.TextField(max_length=500)),
                ('first_similar_ad_photo', models.TextField(max_length=300)),
                ('first_similar_ad_link', models.TextField(max_length=300)),
                ('first_similar_ad_title', models.TextField(max_length=300)),
                ('first_similar_ad_price', models.TextField(max_length=300)),
                ('first_similar_ad_params', models.TextField(max_length=300)),
                ('second_similar_ad_photo', models.TextField(max_length=300)),
                ('second_similar_ad_link', models.TextField(max_length=300)),
                ('second_similar_ad_title', models.TextField(max_length=300)),
                ('second_similar_ad_price', models.TextField(max_length=300)),
                ('second_similar_ad_params', models.TextField(max_length=300)),
                ('third_similar_ad_photo', models.TextField(max_length=300)),
                ('third_similar_ad_link', models.TextField(max_length=300)),
                ('third_similar_ad_title', models.TextField(max_length=300)),
                ('third_similar_ad_price', models.TextField(max_length=300)),
                ('third_similar_ad_params', models.TextField(max_length=300)),
                ('fourth_similar_ad_photo', models.TextField(max_length=300)),
                ('fourth_similar_ad_link', models.TextField(max_length=300)),
                ('fourth_similar_ad_title', models.TextField(max_length=300)),
                ('fourth_similar_ad_price', models.TextField(max_length=300)),
                ('fourth_similar_ad_params', models.TextField(max_length=300)),
                ('fifth_similar_ad_photo', models.TextField(max_length=300)),
                ('fifth_similar_ad_link', models.TextField(max_length=300)),
                ('fifth_similar_ad_title', models.TextField(max_length=300)),
                ('fifth_similar_ad_price', models.TextField(max_length=300)),
                ('fifth_similar_ad_params', models.TextField(max_length=300)),
                ('sixth_similar_ad_photo', models.TextField(max_length=300)),
                ('sixth_similar_ad_link', models.TextField(max_length=300)),
                ('sixth_similar_ad_title', models.TextField(max_length=300)),
                ('sixth_similar_ad_price', models.TextField(max_length=300)),
                ('sixth_similar_ad_params', models.TextField(max_length=300)),
                ('seventh_similar_ad_photo', models.TextField(max_length=300)),
                ('seventh_similar_ad_link', models.TextField(max_length=300)),
                ('seventh_similar_ad_title', models.TextField(max_length=300)),
                ('seventh_similar_ad_price', models.TextField(max_length=300)),
                ('seventh_similar_ad_params', models.TextField(max_length=300)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='av_app.thirdpage')),
            ],
            options={
                'verbose_name': 'Карточка авто',
                'verbose_name_plural': 'Карточки авто',
            },
        ),
    ]
