# Generated by Django 5.0.6 on 2024-07-17 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_app', '0004_usercarrelation_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bookmakers',
            field=models.ManyToManyField(through='av_app.UserCarRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
