import parser_for_general_page
import parser_for_second_page
import parser_for_third_page
import car_card_parser

parser_for_general = parser_for_general_page.ParserForGeneralPage()
parser_for_general_page.ParserForGeneralPage.run(parser_for_general)

parser_for_second = parser_for_second_page.ParserForSecondPage()
parser_for_second_page.ParserForSecondPage.run(parser_for_second)

parser_for_third = parser_for_third_page.ParserForThirdPage()
parser_for_third_page.ParserForThirdPage.run(parser_for_third)

parser_for_car_card = car_card_parser.ParserForCarCard()
car_card_parser.ParserForCarCard.run(parser_for_car_card)

